### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by CapKenR** [n3integration/terraform-godaddy#10]
Any thoughts on supporting Terraform on Windows?

**Comment by n3integration** [comment]
Hey @CapKenR - I hadn't considered Windows, but I don't see why not. I rebuilt v1.3 with Windows binaries as well as v1.4. The latest release also includes support for Terraform 0.10.x. ~Cheers

**Comment by CapKenR** [comment]
That worked. I extracted terraform-godaddy_windows_amd64.exe, renamed it to terraform-provider-godaddy.exe and copied it to the same directory as my terraform.exe.

**Comment by trajano** [comment]
@CapKenR can you provide the steps of doing this?
