### ISSUE TITLE
255 character limit in data

### ISSUE THREAD

**Issue by antgel** [n3integration/terraform-godaddy#13]
On line 101 of `types.go`, data is regarded as invalid if it's longer than 255 characters. This may be a problem with [specific DNS servers](https://kb.isc.org/article/AA-00356/0/Can-I-have-a-TXT-or-SPF-record-longer-than-255-characters.html) but is not forbidden according to RFCs I could find. Certainly GoDaddy supports longer than 255 characters. Can this restriction be lifted? I can't get our DKIM record to work otherwise.

**Comment by n3integration** [comment]
Good call. I've updated the validation to be inline with the standard restrictions.
