### ISSUE TITLE
GoDaddy SOA record suddenly changed

### ISSUE THREAD

**Issue by scream314** [n3integration/terraform-godaddy#17]
As I was executing `terraform plan` on my `godaddy_domain_record` resource, the following change appeared:
```
      record.x.data: "" => ""
      record.x.name: "@" => ""
      record.x.ttl:  "600" => "0"
      record.x.ype: "SOA" => ""
```

Any idea where is this coming from? Should I add a new record to my resource? Like:
```
  record {
    name = "@"
    type = "SOA"
    data = ""
    ttl = 600
  }
```
Checked via GoDaddy API (`/v1/domains/${domain}/records/SOA`) and there is indeed a SOA record:
```
[{"data":"","name":"@","ttl":600,"type":"SOA"}]
```

**Comment by scream314** [comment]
And this SOA record was not present in the response on `/v1/domains/${domain}/records` back in november.

**Comment by scream314** [comment]
If I add
```
  record {
    name = "@"
    type = "SOA"
    data = ""
    ttl = 600
  }
```
to the resource, there is no more any difference. So I think this is the right thing to do.

**Comment by n3integration** [comment]
Hey @scream314 - If the values are supplied by GoDaddy and you don't want to override or remove them, then yes, you should create a matching record type to get the resource and state in sync.
