### ISSUE TITLE
`SRV` entries not supported

### ISSUE THREAD

**Issue by NobbZ** [n3integration/terraform-godaddy#30]
I just managed to `import` my godaddy managed domain, since I want it to be managed by `terraform`.

But I can not work with that, because I have 2 `SRV` entries for SIP support.

I'd like to keep those entries.

Could you please add support for `SRV` entries in your plugin?

**Comment by guessi** [comment]
@n3integration just ran into this issue, and I have created a PR for this fix, could you please kindly review this change? thanks
