### ISSUE TITLE
ns_record block (or similar) proposal

### ISSUE THREAD

**Issue by polds** [n3integration/terraform-godaddy#4]
Wondering if it'd be appropriate to add another supported block called `ns_record` that can take a list and assumes name to be `@` and optional TTL. Use case could follow something like so:

```
variable "domain" {
   default = "google.com"
}

resource "aws_route53_zone" "mydomain" {
   name = "${var.domain}"
}

resource "godaddy_domain_record" "mydomain" {
   domain = "${var.domain}"

   ns_record {
      name_servers = ["${aws_route53_zone.mydomain.name_servers}"]
   }
}
```

**Comment by n3integration** [comment]
I feel like this would be a great change to the API. Rather than limit to `ns_record`, it may be generified similar to the following:
```go
record_list {
  type = "NS"
  list = ["${aws_route53_zone.mydomain.name_servers}"]
}
```
This would allow for updating MX records in a similar manner. In addition to `name` and `TTL` having default options, the `type` could have a default value of `NS` to simply your example configuration. Thoughts?

**Comment by polds** [comment]
I like the idea. MX could prove rough due to priorities. But a list of A and NS could be neat.

**Comment by n3integration** [comment]
Although the syntax is slightly different than the initial suggestion, I've incorporated the feature as 
```go
resource "godaddy_domain_record" "mydomain" {
   domain = "${var.domain}"

   ns_servers = ["${aws_route53_zone.mydomain.name_servers}"]
}
```
One downside, would be if you wanted to change the TTL, you would have to fallback to a `record` for each nameserver. If this works for you, feel free to close out the issue. Thanks!

**Comment by polds** [comment]
I like it! Thanks!

**Comment by polds** [comment]
Just got around to implementing this, `record` is still listed as a required field even with `ns_records` being set.

**Comment by n3integration** [comment]
No worries. You're absolutely right. I relaxed the constraint. While I was at it, I modified the syntax slightly to better clarify the intent. If this change works for you, feel free to close out the issue. Thanks again for your contributions! 

`a_records` => `addresses`
`ns_records` => `nameservers`

**Comment by polds** [comment]
Looks good! Thanks again.
