### ISSUE TITLE
429's shouldn't be a hard error

### ISSUE THREAD

**Issue by polds** [n3integration/terraform-godaddy#6]
Me again :(

I'm working with a Terraform module that updates close to 200 domains using this, after awhile it begins to throw `429 - Too many requests` from GoDaddy. I'm thinking the module should gracefully handle this and backoff as it's not a true error.

Providing my workload today, I'll see if I can get a PR for this up.

**Comment by n3integration** [comment]
It looks like requests are rate limited at ~1/sec. Requests are now being throttled. It looks like requests roughly take anywhere between 400ms to 1+s. This may potentially slow down clients who are submitting less than 60 requests, but it gives linear results independent of the number of requests sent and should be barely noticeable – ymmv. You can grab the latest release [here](https://github.com/n3integration/terraform-godaddy/releases/tag/v1.2.1).
